### ISSUE TITLE
The website doesn't work on Firefox

### ISSUE THREAD

**Issue by quasiyoke** [pedronauck/docz-website#50]
On Firefox https://www.docz.site/ flashes with its header for a fraction of second and disappears. Was checked on Firefox 66 (64 bit) on Ubuntu and on Mac OS with different network connections. The website works on Chromium on the same machines correctly.

![](https://i110.fastpic.ru/big/2019/0324/50/65b371d22dc83e428c20bfbc2ed7d250.png)

**Comment by kachkaev** [comment]
Same here on macOS

## With Content blocking (configured by default)

![Screenshot 2019-03-25 at 13 08 51](https://user-images.githubusercontent.com/608862/54922197-92523980-4eff-11e9-82e8-a9d18740841b.png)


## With Content blocking manually turned off for `docz.site`

![Screenshot 2019-03-25 at 13 10 37](https://user-images.githubusercontent.com/608862/54922175-88c8d180-4eff-11e9-9393-e248dca87206.png)

## About Firefox

<img width="708" alt="Screenshot 2019-03-25 at 13 09 43" src="https://user-images.githubusercontent.com/608862/54922211-99794780-4eff-11e9-93c1-8bfcd17a5393.png">

**Comment by macklinu** [comment]
Looks like the `SecurityError: The operation is insecure.` is related to using websockets. Here is a screenshot of the line that threw the error in docz.site:

![image](https://user-images.githubusercontent.com/2344137/54958476-00ecc280-4f13-11e9-9fc5-63b6f2aeb709.png)

Following the advice in this SO post that recommends [setting `network.websocket.allowInsecureFromHTTPS` to true in `about:config`](https://stackoverflow.com/a/12042843), I was able to get docz.site to load in Firefox.

Not sure what the fix is for this site right now, but I hope this information helps narrow down the bug source.

**Comment by sw-yx** [comment]
just a heads up that ongoing dev is at the v1 branch: https://github.com/pedronauck/docz-website/tree/v1 and we should prob check firefox there cc @pedronauck

**Comment by jwhitley** [comment]
I can repro this in Firefox v60 ESR, so it's not just a problem with the most recent release.

**Comment by pedronauck** [comment]
No @sw-yx, was by mad... I forgot to delete the `v1` branch, `master` is already merged. I need to check how fix this insecure warning :sad:

**Comment by pluma** [comment]
![Firefox stacktraces](https://user-images.githubusercontent.com/1280922/55266619-45af8b00-527e-11e9-90bb-9109f4b84e71.png)

Attaching the stacktraces for completeness' sake.

In Chrome I'm seeing this instead:

![Chrome stacktrace](https://user-images.githubusercontent.com/1280922/55266765-e140fb80-527e-11e9-913f-45ad5528b4ca.png)

I'm guessing this is the culprit:

```js
useDataServer('ws://127.0.0.1:60505')
```

This probably shouldn't be in production code.

**Comment by pedronauck** [comment]
Fixed ✅
